##emall-gate##
server:
  port: 8809
spring:
  application:
    name: emall-gate
# 注册中心待配置 请在本地启动
  cloud:
    consul:
      host: http://127.0.0.1
      port: 8500
      discovery:
        healthCheckPath: /health
        instance-id: id-emall-gate
        health-check-interval: 10s
  jackson:
    default-property-inclusion: ALWAYS
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss

  #------------------------redis------------------------------
  #Redis 单机配置
  redis:
    password: 190814
    timeout: 10000
    host: 120.79.213.244
    port: 6379

  #------------DruidDataSource config --------------------------------
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://xiaoxia1.mysql.rds.aliyuncs.com:3306/emall_user?zeroDateTimeBehavior=convertToNull
    username: xiaoxiao
    password: Java@2018





