##emall-wap##
server:
  port: 8801
spring:
  application:
    name: emall-wap
# 注册中心待配置
  cloud:
    consul:
      host: 120.79.213.244
      port: 8500
      discovery:
        healthCheckPath: /health
        healthCheckInterval: 15s
        instance-id: id-emall-wap
  jackson:
    default-property-inclusion: ALWAYS
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss

  #------------------------redis------------------------------
  #Redis 单机配置
  redis:
    password: 190814
    timeout: 10000
    host: 120.79.213.244
    port: 6379

  #------------DruidDataSource config --------------------------------
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url:jdbc: mysql://xiaoxia1.mysql.rds.aliyuncs.com:3306/xiaoxiaodemo?zeroDateTimeBehavior=convertToNull
    username: xiaoxiao
    password: Java@2018





