##emall-wap##
server:
  port: 8801
spring:
  application:
    name: emall-wap
# 注册中心待配置 请在本地启动
  cloud:
    consul:
      host: http://127.0.0.1
      port: 8500
      discovery:
        healthCheckPath: /health
        instance-id: id-emall-wap
        health-check-interval: 10s
  jackson:
    default-property-inclusion: ALWAYS
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss

  #------------------------redis------------------------------
  #Redis 单机配置
  redis:
    password: 190814
    timeout: 10000
    host: 120.79.213.244
    port: 6379

  #------------DruidDataSource config --------------------------------
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://xiaoxia1.mysql.rds.aliyuncs.com:3306/emall_wap?zeroDateTimeBehavior=convertToNull
    username: xiaoxiao
    password: Java@2018

mybatis-plus:
  # 配置扫描xml
  mapper-locations: classpath:com/emall/wap/mapper/xml/*.xml
  # 实体扫描，多个package用逗号或者分号分隔
  type-aliases-package: com.emall.wap.mapper